# docker-compose.yml

version: '3.8'

services:
  # The Node.js backend service
  backend:
    # Use the image from the GitLab registry, with the tag passed via the .env file
    image: ${BACKEND_IMAGE}
    container_name: my-app-backend

  # The React frontend service
  frontend:
    # Use the image from the GitLab registry
    image: ${FRONTEND_IMAGE}
    container_name: my-app-frontend

  # The Nginx reverse proxy service
  proxy:
    image: nginx:stable-alpine
    container_name: my-app-proxy
    ports:
      # Map port 80 of the host machine to port 80 of the proxy container
      - "80:80"
    volumes:
      # Mount our custom nginx config into the container
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # Wait for the backend and frontend services to start before starting the proxy
      - backend
      - frontend
